## Codebook institutions

| Nr | Variable | Variablenbeschreibung | Variablenwerte (NA = keine Information verfügbar) | Vorgehen | Quellen | URL Webquellen | Anmerkungen 
| --- | --- | --- | --- | --- | --- | --- |--- |
| 2 | Bundesland | Bundesland, in dem sich die Einrichtung befindet | Baden-Württemberg, Berlin, Brandenburg, Freie Hansestadt Bremen, Freie und Hansestadt Hamburg, Freistaat Bayern, Freistaat Sachsen, Freistaat Thüringen, Hessen, Mecklenburg-Vorpommern, Niedersachsen, Nordrhein-Westfalen, Rheinland-Pfalz, Saarland, Sachsen-Anhalt, Schleswig-Holstein; NA | Abgleich mit GERiT-Liste, ggf. ergänzt | Recherche | 
| 3 | Name der Institution| Bezeichung der Einrichtung | Name | übernommen von Internetseite des Ministeriums, alternativ Name aus GERiT-Liste, ggf. nachrecherchiert, wenn auf keiner Liste oder fehlerhaft auf einer der beiden Listen; alle Fraunhofer-Bezeichnungen aus GERiT-Liste | Webseite Ministerium, GERiT |  
| 4 | Ort | Ort der Einrichtung, GERiT-Liste, ggf. nachrecherchiert | Name; NA | Abgleich mit GERiT-Liste, ggf. ergänzt | GERiT |
| 5 | Institutionstyp | Typ der Institution; eigene Verschlagwortung, für alle von GERiT übernommenen Einrichtungen wurde für alle Hochschulen aus GERiT (Kunst, Musik, Weitere) "Hochschulen" übernommen, für alle "Bundesforschung" wurde "Ressortforschung" übernommen | Universität; Hochschule; Forschungsorganisation; Ressortforschung; Vereinigung; Stiftung; Weitere; NA | Abgleich mit GERiT-Liste, ggf. ergänzt | GERiT |
| 6 | OA-Webseite der Institution | Angabe, ob eine Webseite vorhanden ist, die an der Einrichtung über eigene Services zu und über Open Access informiert | ja; nein | Recherche | Webseite Einrichtung |
| 7 | OA-Webseite der Institution URL | sofern vorhanden, URL der Open-Access-Webseite | URL; NA | Recherche | Webseite Einrichtung |
| 8 | OA-Beauftragte*r | Angabe, ob ein*e Open-Access-Beauftragte*r an der Einrichtung vorhanden ist | ja; nein; kommissarisch | Recherche, Abgleich OA2020 und OABB | OA2020, OABB | https://oa2020-de.org/pages/uebersichtoabeauftragte; http://www.open-access-berlin.de/ressourcen | 
| 9 | OA-Beauftragte*r Name | Name (ggf. mit Titel) der Person, die mit der Funktion Open-Access-Beauftragte*r auf der Webseite aufgeführt ist;  "NN" wenn die Funktion existiert, aber derzeit nicht besetzt ist | Name; NN; NA | Recherche, Abgleich OA2020 und OABB | OA2020, OABB | https://oa2020-de.org/pages/uebersichtoabeauftragte; http://www.open-access-berlin.de/ressourcen | Spalte "Anmerkungen" (intern) muss noch gesichtet werden |
| 10 | OA-Beauftragte*r Kontakt URL | Sofern vorhanden, URL der Webseite, auf der die direkten Kontaktdaten der*des Open-Access-Beauftragte*n einsehbar sind | URL; NA | Recherche | Webseite Einrichtung | 
| 11 | OA-Beauftragte*r Quelle URL | sofern vorhanden, URL der Webseite, auf der die*der Open-Access-Beauftragte benannt wird | URL; NA | Recherche, Abgleich OA2020 und OABB | OA2020, OABB | https://oa2020-de.org/pages/uebersichtoabeauftragte; http://www.open-access-berlin.de/ressourcen |
| 12 | Ansprechperson für OA | Angabe, ob eine/mehrere Ansprechperson/en an der Einrichtung vorhanden ist/sind | ja; nein | Recherche | Webseite Einrichtung | 
| 13 | Ansprechperson für OA URL | sofern vorhanden, URL der Webseite, auf der die/der Ansprechperson/en aufgeführt ist/sind | URL; NA | Recherche | Webseite Einrichtung |
| 14 | (Funktions-)Emailadresse | Öffentlich verfügbare E-Mailadresse, die als Open-Access-Funktionsadresse angegeben wurde; wenn keine Funktionsadresse, dann eine individuelle Adresse | E-Mail (aaa[at]bbb[​dot]xx); NA | Recherche | Webseite Einrichtung | 
| 15 | OA Policy | Angabe, ob eine Open Access Policy oder Leitlinie der Einrichtung vorhanden ist und im Webangebot der Forschungseinrichtung auffindbar und einsehbar ist | ja; ja, als MPG; ja, als FhG; nein; noch nicht veröffentlicht | Abgleich mit ROAR, ggf. ergänzt | ROAR | http://roarmap.eprints.org/view/country/276.html |
| 16 | OA Policy Datum | sofern angegeben, Datum der Verabschiedung der Open Access Policy | Datum; NA | Recherche | Webseite Einrichtung | 
| 17 | OA Policy URL | Sofern vorhanden, Persistent Identifier oder (wenn nicht vorhanden, dann) URL der Webseite der veröffentlichten Open Access Policy bzw. der Information über die Verabschiedung der Open Access Policy oder (wenn nicht vorhanden, dann) PDF-Fomat | URL; NA | Recherche | Webseite Einrichtung | 
| 18 | OA-Strategie | Angabe, ob eine Open-Access-Strategie o.ä. ergänzend zu einer Open Access Policy der Einrichtung vorhanden ist und im Webangebot der Forschungseinrichtung auffindbar und einsehbar ist | ja; nein | Recherche | Webseite Einrichtung |
| 19 | OA-Strategie Datum | Sofern angegeben, Datum der Verabschiedung der Open-Access-Leitlinie/Open-Access-Richtlinie/Open-Access-Strategie | Datum; NA | Recherche | Webseite Einrichtung | 
| 20 | OA-Strategie URL | Sofern vorhanden, URL der Webseite, auf der eine Leitlinie nachgelesen werden kann (alternative Bezeichnungen: Handlungsrichtlinie, Resolution, Leitfaden) | URL; NA | Recherche | Webseite Einrichtung |
| 21 | OS Policy | Angabe, ob eine Open Access Policy der Einrichtung vorhanden ist und im Webangebot der Forschungseinrichtung auffindbar und einsehbar ist. | ja; nein | Reecherche | Webseite Einrichtung |
| 22 | OS Policy Datum | Sofern angegeben, Datum der Verabschiedung der Open Science Policy | Datum; NA | Recherche | Webseite Einrichtung | 
| 23 | OS Policy URL | Sofern vorhanden, URL der Webseite der veröffentlichten Open Science Policy bzw. der Information über die Verabschiedung der Open Science Policy | URL; NA | Recherche | Webseite Einrichtung | 
| 24 | Zs. Publikationsfonds | Angabe, ob ein Publikationsfonds für Zeitschriftenartikel vorhanden ist | ja; nein | Recherche | Webseite Einrichtung | 
| 25 | Zs. Publikationsfonds URL | Sofern vorhanden, dann URL der Webseite, auf der Informationen zum Publikationsfonds Zeitschriften hinterlegt sind | URL; NA | Recherche | Webseite Einrichtung |
| 26 | Zs. Publikationsfonds Art der Finanzierung | Angabe, wie der Publikationsfonds für Zeitschriften finanziert wird | DFG-Kofinanziert; EU; Eigenmittel; Eigenmittel, medizinische Fakultät, MWK des Landes Baden-Württemberg ; über WGL Publikationsfonds; Landeskofinanziert; MWK-Kofinanziert; über die MPG; über FhG Publikationsfonds; NA | Recherche | Webseite Einrichtung |
| 27 | Zs. Publikationsfonds Kriterien | tbd | Gold OA; Gold und hybrid OA; bis 2000 EUR (inkl. MwSt.); über 2000 EUR anteilig; bis 1000 EUR (inkl. MwSt.); über 1000 EUR anteilig; über 2.000 EUR: Pauschal xxxx EUR (zzgl. MwSt.);  max. 2000 EUR (inkl. MwSt.) p.P p.J.; anteilige Förderung (xx%); "submitting" oder "corresponding author"; "corresponding author";  offene Lizenz; CC-Lizenz; Repositorium; DOAJ-indexiert; abweichende Kriterien für Fachbereiche; für Nachwuchswissenschaftler volle Kostenübernahme; keine Drittmittel; keine Mirror Journals; X Artikel p.J. / p.P.; Impactfactor (JIF) > 10; ORCID | Recherche | Webseite Einrichtung | 
| 28 | Zs. Publikationsfonds weitgehend DFG-Kriterien | tbd
| 29 | Zs. Publikationsfonds abweichende Kriterien | tbd
| 30 | Zs. Publikationsfonds abweichende Förderung | tbd
| 31 | Mono. Publikationsfonds | Angabe, ob ein Publikationsfonds für Monografien/Sammelbände vorhanden ist | ja; nein | Recherche | Webseite Einrichtung 
| 32 | Mono. Publikationsfonds URL | Sofern vorhanden, dann URL der Webseite, auf der Informationen zum Publikationsfonds für Monografien/Sammelbände hinterlegt sind | URL; NA | Recherche | Webseite Einrichtung |
| 33 | Repositorium | Angabe, ob ein Repositorium vorhanden ist | ja; nein; andere | Recherche | Webseite Einrichtung | 
| 34 | Repositorium URL | Sofern vorhanden, URL zum Repositorium, das von der Einrichtung betrieben wird | URL; NA | Recherche | Webseite Einrichtung |
| 35 | Repositorium andere URL | Sofern vorhanden, URL zu weiterem Repositorium, dessen Nutzung von der Einrichtung empfohlen wird bzw. als kollaborativ genutzter Hostingdienst genutzt wird | URL; NA | Recherche | Webseite Einrichtung | 
| 36 | OA-Verlag | Angabe, ob die Einrichtung einen eigenen Open-Access-Verlag betreibt | ja; nein | Recherche, Abgleich Liste AG Univerlage | https://ag-univerlage.de/?page_id=535 | 
| 37 | OA-Verlag URL | Sofern vorhanden, URL der Website des Open-Access-Verlags | URL; NA | Recherche, Abgleich Liste AG Univerlage | https://ag-univerlage.de/?page_id=535 |
| 38 | OJS Standort | Angabe, ob die Einrichtung ein eigenes Open Journal System Hosting betreibt | ja; nein | Recherche, Abgleich Liste OJS-Standorte | https://ojs-de.net/netzwerk/ojs-standorte-im-deutschsprachigen-raum |
| 39 | OJS Standort URL| Sofern vorhanden, URL der Website mit Informationen zum Open Journal System Hosting | URL; NA | Recherche, Abgleich Liste OJS-Standorte | https://ojs-de.net/netzwerk/ojs-standorte-im-deutschsprachigen-raum | 
| 40 | OA-/OS-Preis | Angabe, ob die Einrichtung einen Open-Access-/Open-Science-Preis verliehen wird | ja; nein | Recherche | Webseite Einrichtung |
| 41 | OA-/OS-Preis Kategorie | Angabe, wofür ein Open-Access-/Open-Science-Preis verliehen wird | beschreiben; NA | Recherche | Webseite Einrichtung | 
| 42 | OA-/OS-Preis URL | Sofern vorhanden, URL der Website mit Informationen zu Open-Access-/Open-Science-Preis an der Einrichtung | URL; NA | Recherche | Webseite Einrichtung |
| 43 | Berliner Erklärung | Angabe, ob und über welche Organisation die Einrichtung die Berliner Erklärung unterzeichnet hat | ja; nein; ja, als HFG; ja, als MPG;  ja, als FhG; ja, als WGL; ja (Uni Hamburg) | übernommen von Liste Berlin Declaration Signatories | MPG Berlin Declaration Signatories | 
| 44 | Berliner Erklärung Datum Unterzeichnung | Datum der Unterzeichnung der Berliner Erklärung | Datum; NA | übernommen von Liste Berlin Declaration Signatories | MPG Berlin Declaration Signatories | https://openaccess.mpg.de/3883/Signatories | 
| 45 | OA2020 Expression of Interest | Angabe, ob die Einrichtung die Expression of Interest von OA2020 unterzeichnet hat | ja; nein; ja, als WGL; ja, als MPG; "ja, als HGF"; "ja, als FhG" | Abgleich OA2020 | OA2020 | https://oa2020.org/mission/ | 
| 46 | OA2020 Expression of Interest Datum Unterzeichnung | Datum der Unterzeichnung OA2020 Expression of Interest | Datum; NA | Abgleich OA2020 | OA2020 | https://oa2020.org/mission/ | 
| 47 | DORA Institution | Angabe, ob die Einrichtung DORA unterzeichnet hat | ja; nein | Abgleich DORA | DORA | https://sfdora.org/signers/ |
| 48 | Jussieu | Angabe, ob die Einrichtung den Jussieu-Appell unterzeichnet hat | ja; nein | Abgleich Jussieu | NA | https://jussieucall.org/jussieu-appell/
| 49 | aktualisiert am | Datum der letzten Recherche aller Open-Access-Angaben | Datum | Recherche |
| 50 | Bearbeiter*in | Kürzel der Person, die den Eintrag der Institution zuletzt bearbeitet hat | MK, LM, MN, SK | 
| 51 | Name (Website Ministerium) | Bezeichung der Einrichtung; von Internetseite des Ministeriums (auf diesen Internetseiten sind staatliche und staatlich anerkannte Hochschulen in kirchlicher Trägerschaft erfasst)  bzw. nach den Angaben auf den Internetseiten der Forschungsorganisationen zu den Mitglieder-Einrichtungen | | Recherche | Baden-Württemberg: https://mwk.baden-wuerttemberg.de/de/hochschulen-studium/hochschullandschaft/; Bayern: https://www.stmwk.bayern.de/wissenschaftler/hochschulen.html; Berlin: https://www.berlin.de/sen/wissenschaft/einrichtungen/hochschulen/; Brandenburg: https://mwfk.brandenburg.de/mwfk/de/wissenschaft/hochschule; Bremen: XXX; Hamburg: https://www.hamburg.de/bwfgb/hochschullandschaft-hamburg/12785974/staatliche-hochschulen/; Hessen: https://wissenschaft.hessen.de/wissenschaft/hochschulen-hessen; Mecklenburg-Vorpommern: https://www.regierung-mv.de/Landesregierung/bm/Wissenschaft/Hochschule/; Niedersachsen: https://www.mwk.niedersachsen.de/startseite/hochschulen/hochschullandschaft/hochschulen-berufsakademien-19117.html; Nordrhein-Westfalen: https://www.mkw.nrw/hochschule-und-forschung/studium-und-lehre/ueberblick-hochschulen-nrw; Rheinland-Pfalz: https://mwwk.rlp.de/de/themen/wissenschaft/studieren-in-rheinland-pfalz/hochschulen-in-rheinland-pfalz/; Saarland: https://www.saarland.de/stk/DE/portale/wissenschaftforschungtechnologie/informationen/institutionen/institutionen_node.html; Sachsen-Anhalt: https://mw.sachsen-anhalt.de/themen/hochschulen/hochschulen-in-sachsen-anhalt/; Sachsen: https://www.studieren.sachsen.de/universitaten-kunsthochschulen-hochschulen-fur-angewandte-wissenschaften-und-die-berufsakademie-3909.html; Schleswig-Holstein: https://www.schleswig-holstein.de/DE/Fachinhalte/H/hochschule_allgemein/Wrapping/hochschulen_wrapping.html; Thüringen: https://wirtschaft.thueringen.de/wissenschaft | 
| 52 | Ort | Ort der Einrichtung, GERiT-Liste, ggf. nachrecherchiert | Name; NA | Abgleich mit GERiT-Liste, ggf. ergänzt | Webseite Einrichtung | 
| 53 | Affiliation RoR | Bezeichung der Einrichtung via ROR data dump | Name; NA | Abgleich mit ROAR, ggf. ergänzt | ROR | https://figshare.com/collections/ROR_Data/4596503 (12.04.2021) | 
| 54 | ROR ID | ROR ID der Einrichtung via ROR data dump | ROR ID; NA | Abgleich mit ROAR, ggf. ergänzt | ROR | https://figshare.com/collections/ROR_Data/4596503 (12.04.2021) | 
| 55 | GRID ID | GRID ID der Einrichtung | GRID ID; NA | Abgleich mit GRID, ggf. ergänzt | GRID | https://www.grid.ac/downloads  (1.6.2021) | 
| 56 | Wikidata ID | Wikidata ID der Einrichtung | Wikidata ID; NA | Abgleich mit GRID, ggf. ergänzt | GRID | https://www.grid.ac/downloads  (1.6.2021) | 
| 57 | Trägerschaft Hochschulkompass| Trägerschaft aller Hochschulen (siehe Institutionstyp) | Hochschulkompass | Abgleich mit Liste Hochschulkompass, ggf. ergänzt | Liste Hochschulkompass (Tabellenblatt in diesem Datensatz) | https://www.hochschulkompass.de/hochschulen/downloads.html (13.9.2021) | 
| 58 | Institutionstyp | Typ der Institution; eigene Verschlagwortung, für alle von GERiT übernommenen Einrichtungen wurde für alle Hochschulen aus GERiT (Kunst, Musik, Weitere) "Hochschulen" übernommen, für alle "Bundesforschung" wurde "Ressortforschung" übernommen | Universität; Hochschule; Forschungsorganisation; Ressortforschung; Vereinigung; Stiftung; Weitere; NA | Abgleich mit GERiT-Liste, ggf. ergänzt | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) | 
| 59 | URL Webseite Institution | URL der Webseite der Einrichtung; von GERiT-Liste übernommen, wenn Einrichtung nicht auf Liste der Ministerien | URL | Abgleich mit GERiT-Liste, ggf. ergänzt | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) | 
| 60 | Name GERiT | Bezeichung der Einrichtung aus der GERiT-Liste der DFG; nur Einrichtungen aus Deutschland wurden übernommen | Name; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) |
| 61 | Name GERiT English | engl. Bezeichnung der Einrichtung aus der GERiT-Liste der DFG | Name; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) | Instituts ID; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) | 
| 62 | DFG Instituts ID GERiT | DFG Instituts-ID via GERiT | Instituts ID; NA | DFG Instituts-ID via GERiT | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) | 
| 63 | GRID ID GERiT | GRID ID der Einrichtung via GERiT | GRID ID; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) | 
| 64 | Straße GERiT | Straße (Anschrift) | Name; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) | 
| 65 | Hausnummer GERiT | Hausnummer (Anschrift) | Nummer; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) |
| 66 | Postfach GERiT | Postfach (Anschrift) | Nummer; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) |
| 67 | Postleitzahl nach Ort GERiT | Postleitzahl (Anschrift) | Nummer; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) |
| 68 | Ort GERiT | Ort (Anschrift) | Nummer; NA | übernommen aus GERiT-Liste | GERiT | Nummer; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) |
| 69 | DESTATIS Fächergruppe GERiT | Fächergruppe DESTATIS via GERiT-Liste | Nummer; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) |
| 70 | DESTATIS Lehr- und Forschungsbereich GERiT | Lehr- und Forschungsbereich via GERiT-Liste | Nummer; NA | übernommen aus GERiT-Liste | GERiT |
| 71 | DESTATIS Fachgebiet GERiT | Fachgebiet via GERiT-Liste | Nummer; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) |
| 72 | Crossref ID GERiT | Crossref ID via GERiT-Liste | CrossRef ID; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) |
| 73 | GERiT ID | GERiT ID via GERiT-Liste | GERiT ID | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) |
| 74 | URL der Einrichtung GERiT | URL der Webseite der Einrichtung via GERiT-Liste | URL; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) |
| 75 | Einrichtungsart GERIT English | engl. Bezeichnung für Typ der Einrichtung via GERiT | Academies; federal research; university; Helmholtz; Leibniz; Max Planck; Fraunhofer; other res. inst.; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) |
| 76 | Einrichtungsart GERiT | Typ der Einrichtung via GERiT | Akad. d. Wiss.; Bundesforschung; Dt. Fördereinrichtung; FhG; HGF; WGL; MPG; Musik/Kunst-HS; Sonst. Forschung; NA | übernommen aus GERiT-Liste | GERiT | https://www.gerit.org/de/service/%22 (5. März 2021) |
